<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenSearchSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b3a84949-3e31-4d59-a257-d10c5eed8785</testSuiteGuid>
   <testCaseLink>
      <guid>7beaf1af-8910-4877-9cc5-c672cf8c2bfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>6dded272-89b5-4f02-8d33-97d5e2322a42</id>
         <masked>false</masked>
         <name>SearchKeyword</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/SearchProduct/SearchProductWithCsvDataFile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>56c2a007-9367-4884-85ee-4ca6e3dbc0bc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/SearchKeyword/DataBinding</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>56c2a007-9367-4884-85ee-4ca6e3dbc0bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SearchKeyword</value>
         <variableId>6dded272-89b5-4f02-8d33-97d5e2322a42</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
