<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>cef387b4-eb77-4837-9189-0ba6393e61eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.auto.cell > ul.top-nav-module_header-links_1Ovug > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopfront-app']/div[2]/div/div/div[2]/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d81ada02-315a-4c5d-a906-033e4f789ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-react-link</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7685a556-b865-488a-bde6-8922438734a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/login?returnTo=https%3A%2F%2Fwww.takealot.com%2F</value>
      <webElementGuid>be56f3a8-abb9-4d31-a63f-0cf77212eff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>fda93498-df43-4594-9cb7-7dccb9b5d5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopfront-app&quot;)/div[@class=&quot;top-nav top-nav-module_top-nav_2cmJW&quot;]/div[@class=&quot;grid-container top-nav-module_top-strip_2SdJ-&quot;]/div[@class=&quot;grid-x grid-margin-x&quot;]/div[@class=&quot;auto cell&quot;]/div[@class=&quot;grid-x grid-margin-x align-right&quot;]/div[@class=&quot;auto cell&quot;]/ul[@class=&quot;top-nav-module_header-links_1Ovug&quot;]/li[1]/a[1]</value>
      <webElementGuid>39161193-ff7e-41b5-b27b-6a15dc170bd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopfront-app']/div[2]/div/div/div[2]/div/div/ul/li/a</value>
      <webElementGuid>139ab136-fe87-40b8-9efc-b0663f966436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>5631a8a8-b613-452b-947a-f1f86f783805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/login?returnTo=https%3A%2F%2Fwww.takealot.com%2F')]</value>
      <webElementGuid>7e746d7f-ba1c-4692-98bb-e02ba67b57a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/a</value>
      <webElementGuid>49bf6e7c-87e1-4b63-990e-f0cde53da73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/login?returnTo=https%3A%2F%2Fwww.takealot.com%2F' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>407294c1-6028-46df-9499-d66771b8daf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
