<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search</name>
   <tag></tag>
   <elementGuidId>7c46a128-6688-401d-80e1-985bb4fb5402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;search&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac09c0cf-0744-4518-9ecb-bece77437299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>625c4df8-d561-4afa-bf6a-ded25c735179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-field </value>
      <webElementGuid>1ea241f7-bc41-49f5-8082-d105797bf2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>563cb813-17b4-49c1-aa5b-864a65dd914c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for products, brands...</value>
      <webElementGuid>c79cca35-9a72-4247-b80b-70e8ba97c1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopfront-app&quot;)/header[@class=&quot;header-module_header_JPuf4&quot;]/div[@class=&quot;header-main-strip grid-container header-module_main-strip_1mjwO&quot;]/div[@class=&quot;grid-x grid-margin-x&quot;]/div[@class=&quot;auto cell&quot;]/form[1]/div[@class=&quot;input-group search-container grid-x&quot;]/div[@class=&quot;input-group-field search-group cell auto&quot;]/input[@class=&quot;search-field&quot;]</value>
      <webElementGuid>282101d1-ba46-497c-9135-d5d8d0cd0d80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='search']</value>
      <webElementGuid>856afb8d-48f8-439f-88ed-c6a7ed0e1e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopfront-app']/header/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>0c447637-839d-4aff-a866-12bb15d9a752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>aed11b35-fc89-46e3-bba3-478fbeabb7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'search' and @type = 'text' and @placeholder = 'Search for products, brands...']</value>
      <webElementGuid>7012dcdf-aef5-4f93-9d02-55d0dd8f63c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
