<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>a39bc490-11e7-468e-8cd8-2146b95a49d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.auto.cell > ul.top-nav-module_header-links_1Ovug > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopfront-app']/div[2]/div/div/div[2]/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb3b35e0-1199-46c7-97de-1ed678b79376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-react-link</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1634564e-39fc-4ad0-9426-115345c3cf98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/login?returnTo=https%3A%2F%2Fwww.takealot.com%2F</value>
      <webElementGuid>7f029de5-62b3-40e2-95e2-5b5e5ceca72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>2aab01f8-f219-4545-9c01-7cef892096d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopfront-app&quot;)/div[@class=&quot;top-nav top-nav-module_top-nav_2cmJW&quot;]/div[@class=&quot;grid-container top-nav-module_top-strip_2SdJ-&quot;]/div[@class=&quot;grid-x grid-margin-x&quot;]/div[@class=&quot;auto cell&quot;]/div[@class=&quot;grid-x grid-margin-x align-right&quot;]/div[@class=&quot;auto cell&quot;]/ul[@class=&quot;top-nav-module_header-links_1Ovug&quot;]/li[1]/a[1]</value>
      <webElementGuid>97061d68-4d34-4a59-94f9-47840f38ec54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopfront-app']/div[2]/div/div/div[2]/div/div/ul/li/a</value>
      <webElementGuid>4cb430c0-017d-46bd-8048-fe8133262cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>22347484-5e68-4eb3-893e-09cb6d212a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/login?returnTo=https%3A%2F%2Fwww.takealot.com%2F')]</value>
      <webElementGuid>c7658f00-0f81-48a9-a9cd-61056ad6b0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/a</value>
      <webElementGuid>00372bea-26b1-41ec-bdf3-54e8538b59e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/login?returnTo=https%3A%2F%2Fwww.takealot.com%2F' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>6fa43ece-fcb0-490d-bb37-21f62cf3f8fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
