<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout</name>
   <tag></tag>
   <elementGuidId>3c20fbd5-7917-4368-a540-5c26b3633574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > button.top-nav-module_button-link_3JRg7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopfront-app']/div[2]/div/div/div[2]/div/div/ul/li[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>421ec239-babc-4088-943d-44eb1d927ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>logout-btn</value>
      <webElementGuid>6eb55c4f-7a71-4472-855e-d003a8add7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-nav-module_button-link_3JRg7</value>
      <webElementGuid>e3df77cb-527f-4888-bae4-f826e399f8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>c34e9f1a-8d9e-4679-909e-a2ca848e1364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopfront-app&quot;)/div[@class=&quot;top-nav top-nav-module_top-nav_2cmJW&quot;]/div[@class=&quot;grid-container top-nav-module_top-strip_2SdJ-&quot;]/div[@class=&quot;grid-x grid-margin-x&quot;]/div[@class=&quot;auto cell&quot;]/div[@class=&quot;grid-x grid-margin-x align-right&quot;]/div[@class=&quot;auto cell&quot;]/ul[@class=&quot;top-nav-module_header-links_1Ovug&quot;]/li[2]/button[@class=&quot;top-nav-module_button-link_3JRg7&quot;]</value>
      <webElementGuid>5ab732c1-a428-40bc-85c5-3280958ed7b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopfront-app']/div[2]/div/div/div[2]/div/div/ul/li[2]/button</value>
      <webElementGuid>71f041ed-b796-4730-9b5b-7df6e96b3c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>f73c7ad4-30ef-48a9-9261-f7820b0c4ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>e2609dd9-847b-4471-9ac2-c860be5d227c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
