<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>6f8514c3-3c5c-4f48-ba61-9c794a5a1903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.submit-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>756ba1df-51ea-4320-ada5-e71b7bad7fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button submit-action</value>
      <webElementGuid>ef700a98-acf3-45fb-b216-5b594652397f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0470c1e1-5796-4c2a-a5ef-d4463ff323ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>dynaform-submit-button</value>
      <webElementGuid>705250a3-fb71-42c4-9fe0-595073ba5712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>be7e7825-d765-466f-843a-196547323b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[5]/div[@class=&quot;modal-wrapper modal-wrapper-auth-modal undefined modal-module_modal-wrapper_23HFN&quot;]/div[@class=&quot;modal-module_modal-container_fBbBL modal-module_with-close_2b3bC&quot;]/div[@class=&quot;modal auth-modal medium modal-module_modal_OOLjP&quot;]/div[@class=&quot;modal-body modal-module_modal-body_81lrM&quot;]/div[@class=&quot;modal-content modal-module_modal-content_3tE7B modal-module_scrolling_1xj44&quot;]/div[@class=&quot;scroll-wrapper&quot;]/div[1]/div[@class=&quot;login-form login login-module_panel_1oMlb&quot;]/div[@class=&quot;login-form  login-module_login-form_2gq4Q login-module_form-container_1K_p-&quot;]/div[@class=&quot;dyna-form-module_dyna-form_3FUX5&quot;]/form[1]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell auto dyna-form-module_button-cell_1iSdA&quot;]/button[@class=&quot;button submit-action&quot;]</value>
      <webElementGuid>6e661b14-3452-4850-9c4c-bfc67f900736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>490ef8ce-5932-4d3d-8e9e-02a0867e5e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[5]/div/div/div/div/div/div/div/div/div/div/form/div[6]/div/button</value>
      <webElementGuid>99a90397-7732-4785-aa20-732a398bf7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/button</value>
      <webElementGuid>4adef6a0-a87c-4ce4-8ae9-fcf28bacdf30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>a5ebf7ec-1c7d-4601-9004-1b0fd8fe5828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
