<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>71425a56-95de-4b8f-829a-ffc7f5a957db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_login_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_login_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d032317-b6df-42ff-9e7c-4fb64a8dfad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>547f22a6-039c-4356-8ae3-d5fbfa27327a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9d265862-186f-43e9-be9d-108f9ec38b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_login_password</value>
      <webElementGuid>32a687b0-6b4e-4cd9-8e11-65752fc96e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e6a834be-c0ec-48f6-843c-1ad9dcdb4550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login_password&quot;)</value>
      <webElementGuid>2b2684e5-a78d-40cf-af84-3c5417920725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_login_password']</value>
      <webElementGuid>1c3574f5-5cc6-4e7a-8d4c-6b86cf986f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[5]/div/div/div/div/div/div/div/div/div/div/form/div[4]/div[2]/div/div/label/div[2]/div/div/input</value>
      <webElementGuid>84a1febb-6f17-407b-a270-31ad134f2186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/div[2]/div/div/input</value>
      <webElementGuid>39d5d661-8404-4ae6-bcd5-bc5cbc21288a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @type = 'password' and @id = 'customer_login_password']</value>
      <webElementGuid>91725a63-35cf-4efd-a26f-6c2c5a0e4ecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
