<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>3b644eef-b082-4cf2-b418-d4c88cb4878b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.auto.cell > ul.top-nav-module_header-links_1Ovug > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopfront-app']/div[2]/div/div/div[2]/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5937a34b-afc9-449a-b355-a53662708fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-react-link</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c869d340-c7de-484d-ab8d-39a9b81158b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/login?returnTo=https%3A%2F%2Fwww.takealot.com%2F</value>
      <webElementGuid>0b3e5f6f-4fa0-4e3b-a04e-787e594a6e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>649ba8dc-b33e-4245-b11a-a31bdca31646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopfront-app&quot;)/div[@class=&quot;top-nav top-nav-module_top-nav_2cmJW&quot;]/div[@class=&quot;grid-container top-nav-module_top-strip_2SdJ-&quot;]/div[@class=&quot;grid-x grid-margin-x&quot;]/div[@class=&quot;auto cell&quot;]/div[@class=&quot;grid-x grid-margin-x align-right&quot;]/div[@class=&quot;auto cell&quot;]/ul[@class=&quot;top-nav-module_header-links_1Ovug&quot;]/li[1]/a[1]</value>
      <webElementGuid>545039ac-8a42-456d-9ed4-5ad1dee1ee57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopfront-app']/div[2]/div/div/div[2]/div/div/ul/li/a</value>
      <webElementGuid>7f60ee77-ec28-4cab-a5ac-f38a6ee60171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>670587a4-c707-4dd9-9f8c-849377cda272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/login?returnTo=https%3A%2F%2Fwww.takealot.com%2F')]</value>
      <webElementGuid>5ac00911-b501-49c7-a03b-b79451edaf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/a</value>
      <webElementGuid>3f91e4f7-03d9-4590-a4b1-e9ca1c7dcff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/login?returnTo=https%3A%2F%2Fwww.takealot.com%2F' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>85be927b-21c4-46b3-8e1c-cad3bab32138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
