<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>368b072c-5244-4092-8305-7d9f8d79e269</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_login_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_login_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c1325da-7ad6-4652-b778-fb8a2e0433de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>45e2abbd-5e1c-4942-9272-6079570a68a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a8a82fe-4784-4670-8f0b-17037f210932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_login_email</value>
      <webElementGuid>39b6cca6-f2b9-468a-aadc-d20de93fc5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>9b7518a7-9d81-4f09-960e-c7e19d70fcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login_email&quot;)</value>
      <webElementGuid>ce543229-375a-41a3-bf59-b4332c5fada4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_login_email']</value>
      <webElementGuid>a2e86989-92ee-4127-b2d9-bc09567451ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[4]/div/div/div/div/div/div/div/div/div/div/form/div[3]/div/div/div/label/div[2]/div/div/input</value>
      <webElementGuid>aea3366e-07b8-446f-bf46-97e4bde012b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>9b799a40-408c-4bbb-97f0-8fe967cb268d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'text' and @id = 'customer_login_email']</value>
      <webElementGuid>52d1d31c-e7c2-4a07-8ba9-8b8435722b2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
