<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>b3c04695-cc4a-4deb-8970-6ea0f35ecc91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_login_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_login_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e3647fd-f6d0-4b4d-982a-ee47e6a45138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>69e428d9-24de-419d-a3e5-677093a2b013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>40dc1638-8cb0-4b18-b6c1-4f4fc38828d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_login_password</value>
      <webElementGuid>9c080c92-99d1-48f3-8399-336e40cf9ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>14740be2-353c-44ce-9f8e-1c65c655932e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login_password&quot;)</value>
      <webElementGuid>258267ea-01ee-432e-92e0-c846d40cb84e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_login_password']</value>
      <webElementGuid>adbb705e-82e2-463c-847e-deb9d5eac116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[4]/div/div/div/div/div/div/div/div/div/div/form/div[4]/div[2]/div/div/label/div[2]/div/div/input</value>
      <webElementGuid>4630394a-c484-42eb-a4a0-24c840bc9721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/div[2]/div/div/input</value>
      <webElementGuid>95415023-9984-4836-96d4-ba57266cd0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @type = 'password' and @id = 'customer_login_password']</value>
      <webElementGuid>fc733a0a-15c9-4d22-8471-d6c9861e4008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
