<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>748805f6-b9f1-4f18-b2cc-4f3c16f9e10b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopfront-app']/div[2]/div/div/div[2]/div/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.auto.cell > ul.top-nav-module_header-links_1Ovug > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c5500479-3b11-4a77-a7db-b3a90083ba66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-react-link</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57a0fb5c-21c7-43f0-bb13-3ac2ff350273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/register?returnTo=https%3A%2F%2Fwww.takealot.com%2F</value>
      <webElementGuid>883ec3d2-328e-4051-895d-f0f25211e16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>1464d01e-1043-48e5-af49-26557d84f19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopfront-app&quot;)/div[@class=&quot;top-nav top-nav-module_top-nav_2cmJW&quot;]/div[@class=&quot;grid-container top-nav-module_top-strip_2SdJ-&quot;]/div[@class=&quot;grid-x grid-margin-x&quot;]/div[@class=&quot;auto cell&quot;]/div[@class=&quot;grid-x grid-margin-x align-right&quot;]/div[@class=&quot;auto cell&quot;]/ul[@class=&quot;top-nav-module_header-links_1Ovug&quot;]/li[2]/a[1]</value>
      <webElementGuid>d89d52dc-4c38-4385-ad87-0b210ba9831f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopfront-app']/div[2]/div/div/div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>8f754513-e00b-4d46-9a63-05ce5b6e030b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>839b2875-eb9b-44bc-a840-590a378316f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/register?returnTo=https%3A%2F%2Fwww.takealot.com%2F')]</value>
      <webElementGuid>c3af46ce-d5a4-4a8d-a844-7330de948694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>88b3209a-f0ce-4689-838c-ea041964270e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/register?returnTo=https%3A%2F%2Fwww.takealot.com%2F' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>587ed586-e491-47dd-8b6e-a9ca3815d285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
