<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_new_password</name>
   <tag></tag>
   <elementGuidId>3148c39e-7ed5-4211-99e1-d1ee3ad01400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register_customer_new_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#register_customer_new_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>353eb57b-0ac1-4817-8bfc-98a52f2433a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new_password</value>
      <webElementGuid>32c2764e-a5c3-4252-8b8d-23f56948dbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0e0af353-cebb-40b9-9516-fca6fe5d0fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register_customer_new_password</value>
      <webElementGuid>b42ec3a4-9e45-4d49-83e7-2692189c795a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8e95c5d3-c0fa-4060-89b3-df75d9c9a6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_customer_new_password&quot;)</value>
      <webElementGuid>66fab7ae-dfe5-420f-b474-1ab7850c1542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register_customer_new_password']</value>
      <webElementGuid>098fc110-74b0-42dc-a684-c391fe283213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[4]/div/div/div/div/div/div/div/div/div/div/div[3]/form/div[6]/div/div/div/label/div[2]/div/div/input</value>
      <webElementGuid>7475f555-df07-4db9-81f9-18bd6d376ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/label/div[2]/div/div/input</value>
      <webElementGuid>c27a4280-6c28-46bc-b147-43ca265b6623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'new_password' and @type = 'password' and @id = 'register_customer_new_password']</value>
      <webElementGuid>d9ae9176-2d52-4b5d-9543-0ec21096d8ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
