<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mobile_national_number</name>
   <tag></tag>
   <elementGuidId>c8f52ce9-91e4-4ac7-8cd0-7eff8fd817dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register_customer_mobile_national_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#register_customer_mobile_national_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5af24fbb-b013-46f0-ba47-1ac4c16338a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobile_national_number</value>
      <webElementGuid>a6fcea48-bb2e-44f4-9404-b74bd174c943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a4d66cf5-0dae-4988-a51a-c90e202a1af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register_customer_mobile_national_number</value>
      <webElementGuid>a771b946-6c4a-478a-9419-1cb7456fab27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>17ed8a09-03ce-41b4-a9b1-0e360fcf8416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_customer_mobile_national_number&quot;)</value>
      <webElementGuid>1da081d9-3c4b-4d83-928c-89e46d9af5d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register_customer_mobile_national_number']</value>
      <webElementGuid>bf57c3f7-1467-4be8-8471-a4689bf468ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[4]/div/div/div/div/div/div/div/div/div/div/div[3]/form/div[7]/div/div[2]/div/label/div[2]/div/div/input</value>
      <webElementGuid>1e84a4d7-aadf-4f20-8962-5ef113c4ebc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/div[2]/div/div/input</value>
      <webElementGuid>b27ae8a9-b4da-4862-81ac-fe1c02b1399a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'mobile_national_number' and @type = 'tel' and @id = 'register_customer_mobile_national_number']</value>
      <webElementGuid>d3e00c4c-60c5-4865-9d99-3205b803923d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
