<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>da08f008-c3a4-4d01-9f8c-29edc5d81a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register_customer_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#register_customer_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cb7a77b-9161-4848-94f3-f33ea1d0d697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c5b46d04-7e19-4f2d-99c8-2d093be78a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e43693c7-154c-4dab-a582-1685446d6480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register_customer_email</value>
      <webElementGuid>d9be43df-903f-4b19-ac33-0a133da2817c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>7cfe0f52-1310-43c4-ac99-03ab4e6eb56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_customer_email&quot;)</value>
      <webElementGuid>3c8c0c1a-12fe-494a-bbde-278fa6e2ee77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register_customer_email']</value>
      <webElementGuid>6014ce74-151e-4fe0-9e24-c14f5a4603e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[4]/div/div/div/div/div/div/div/div/div/div/div[3]/form/div[5]/div/div/div/label/div[2]/div/div/input</value>
      <webElementGuid>e0074cad-c78e-4d3a-94ca-0eda5741c52c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/label/div[2]/div/div/input</value>
      <webElementGuid>d715a821-1595-4de2-bcd3-28bea8c925c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'text' and @id = 'register_customer_email']</value>
      <webElementGuid>1ac234b3-71f7-45d2-a047-a1ad2b48b624</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
